steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/murugunravi/testrepository', '.']
source:
    git_source:
        url: 'https://github.com/murugunravi/testrepository'
	  dir: 'main'
        revision: 'main'