steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/github_murugunravi_testrepository', '.']
source:
    git_source:
        url: 'https://github.com/murugunravi/testrepository'
        revision: 'main'